#!/bin/bash

# Quick Start Commands for MDRRMO Dashboard
# Run from /app root directory

echo "╔════════════════════════════════════════════════════════════╗"
echo "║    MDRRMO Dashboard - Root-Level Script Commands          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📦 INSTALLATION"
echo "  yarn install:all         - Install all dependencies"
echo "  yarn install:backend     - Install Python dependencies"
echo "  yarn install:frontend    - Install Node.js dependencies"
echo ""
echo "🏗️  BUILD"
echo "  yarn build               - Build frontend for production"
echo ""
echo "🔄 SERVICE MANAGEMENT"
echo "  yarn status              - Check service status"
echo "  yarn restart:all         - Restart all services"
echo "  yarn restart:backend     - Restart backend only"
echo "  yarn restart:frontend    - Restart frontend only"
echo ""
echo "📋 LOGS"
echo "  yarn logs:backend        - View backend logs (live)"
echo "  yarn logs:frontend       - View frontend logs (live)"
echo ""
echo "🧪 TESTING"
echo "  yarn test:backend        - Test backend health endpoint"
echo ""
echo "🧹 CLEANUP"
echo "  yarn clean:cache         - Clean frontend cache"
echo "  yarn clean:all           - Clean everything"
echo ""
echo "🔧 UTILITIES"
echo "  yarn freeze:backend      - Update requirements.txt"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "For detailed documentation, see ROOT_SCRIPTS.md"
echo "═══════════════════════════════════════════════════════════"
